name: Publish Open DnD Docker Image
on:
  release:
    types: [published]
  push:
    tags:
      - '*'
    branch:
      - 'master'
    paths:
      - 'docker/**'
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Copy over the project files for the build
        run: |
          cp api/v1/index.js docker/opendnd-web/
          cp api/v1/package.json docker/opendnd-web/
          cp api/v1/package-lock.json docker/opendnd-web/
      - name: Build and push cli
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: opendnd/cli
          tags: latest 
          tag_with_ref: true
          path: docker/opendnd-cli
      - name: Build and push web
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: opendnd/web
          tags: latest
          tag_with_ref: true
          path: docker/opendnd-web

